/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rp199.template

import com.rp199.template.configuration.AppConfig
import com.rp199.template.configuration.plugin.configureContentNegotiation
import com.rp199.template.configuration.plugin.configureKoin
import com.rp199.template.configuration.plugin.configureMetrics
import com.rp199.template.configuration.plugin.configureMonitoring
import com.rp199.template.configuration.plugin.configureRoutes
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addResourceSource
import io.ktor.serialization.ContentConverter
import io.ktor.server.application.Application
import org.koin.ktor.ext.get

fun main(args: Array<String>) {
    io.ktor.server.netty.EngineMain.main(args)
}


fun Application.configureApp() {
    val config = ConfigLoaderBuilder.default()
        .addResourceSource("/application.conf")
        .build()
        .loadConfigOrThrow<AppConfig>()

    configureMetrics(config)
    configureKoin()
    configureMonitoring(config)
    configureContentNegotiation(converter = get<ContentConverter>())
    configureRoutes()
}