/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rp199.template

import com.rp199.template.configuration.AppConfig
import com.rp199.template.configuration.plugin.installCallLogging
import com.rp199.template.configuration.plugin.installContentNegotiation
import com.rp199.template.configuration.plugin.installKoin
import com.rp199.template.configuration.plugin.installMetrics
import com.rp199.template.configuration.plugin.installRoutes
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addResourceSource
import io.ktor.serialization.ContentConverter
import io.ktor.server.application.Application
import org.koin.ktor.ext.get

fun main(args: Array<String>) {
    io.ktor.server.netty.EngineMain.main(args)
}


fun Application.setup() {
    val config = ConfigLoaderBuilder.default()
        .addResourceSource("/application.conf")
        .build()
        .loadConfigOrThrow<AppConfig>()

    installMetrics(config)
    installKoin()
    installCallLogging(config)
    installContentNegotiation(converter = get<ContentConverter>())
    installRoutes()
}